import { ToolDefinition } from '@/types/tool';

export const MEDIA_ARCHIVE_TOOLS: ToolDefinition[] = [
  // =========================================================================
  // AUDIO SUITE (FFmpeg isolated transcode)
  // =========================================================================
  {
    id: 'audio-konvertieren',
    slug: 'audio-konvertieren',
    category: 'utilities',
    sourceFormats: ['.mp3', '.wav', '.aac', '.flac', '.ogg', '.m4a'],
    targetFormats: ['.mp3', '.wav', '.aac', '.flac', '.ogg', '.m4a'],
    nameDe: 'Audio konvertieren',
    shortDescriptionDe: 'Konvertieren Sie Audiodateien zuverlässig zwischen MP3, WAV, AAC, FLAC, OGG und M4A mit professioneller Bitraten-Wahl.',
    titleDe: 'Audio konvertieren online – MP3, WAV, AAC, FLAC, OGG umwandeln | CoolWave',
    metaDescriptionDe: 'Audiodateien kostenlos online konvertieren. MP3, WAV, AAC, FLAC, OGG und M4A in höchster Klangqualität und mit anpassbarer Bitrate.',
    h1De: 'Audiodateien online konvertieren',
    introDe: 'Konvertieren Sie Ihre Musikstücke, Sprachaufnahmen und Podcasts zwischen den gängigsten Audioformaten. Unterstützt moderne Codecs wie MP3 (LAME), WAV (PCM), AAC, FLAC und OGG (Vorbis) mit wählbarer Bitrate bis zu 256 kbps.',
    howItWorksDe: [
      { step: 1, title: 'Audiodatei hochladen', text: 'Ziehen Sie Ihre MP3-, WAV-, AAC-, FLAC-, OGG- oder M4A-Datei in den Upload-Bereich.' },
      { step: 2, title: 'Zielformat wählen', text: 'Wählen Sie das gewünschte Audioformat und die gewünschte Bitrate (z. B. 192 kbps).' },
      { step: 3, title: 'Konvertieren & Anhören', text: 'Klicken Sie auf Umwandeln, hören Sie die Vorschau direkt im Browser an und laden Sie die Datei herunter.' },
    ],
    faqDe: [
      { question: 'Welches Audioformat bietet die beste Klangqualität?', answer: 'FLAC und WAV sind verlustfreie Formate (Lossless) für maximale Studioqualität. MP3 und AAC bieten hervorragende Kompression für Alltag und Streaming.' },
      { question: 'Gibt es eine maximale Spieldauer?', answer: 'In der kostenlosen Version können Audiodateien bis zu 10 Minuten Länge verarbeitet werden; Pro-Nutzer genießen bis zu 60 Minuten.' },
    ],
    troubleshootingDe: [
      { issue: 'Datei wird nicht erkannt', solution: 'Stellen Sie sicher, dass es sich um eine gültige Audiodatei mit passenden Header-Daten handelt.' },
    ],
    privacyExplanationDe: 'Audiodateien werden in einer isolierten Server-Sandbox transkodiert und nach Abschluss automatisch gelöscht.',
    searchKeywordsDe: ['Audio konvertieren', 'MP3 in WAV umwandeln', 'WAV in MP3', 'FLAC in MP3 konvertieren', 'Audio umwandeln online'],
    supportedFormats: 'MP3, WAV, AAC, FLAC, OGG, M4A',
    freeLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 200, maxBatch: 10 },
    processingEngine: 'media-convert',
    browserCapable: false,
    serverRequired: true,
    relatedTools: ['audio-komprimieren', 'video-in-mp3-umwandeln'],
    icon: 'Music',
    status: 'active',
  },
  {
    id: 'audio-komprimieren',
    slug: 'audio-komprimieren',
    category: 'utilities',
    sourceFormats: ['.mp3', '.wav', '.aac', '.flac', '.ogg', '.m4a'],
    targetFormats: ['.mp3', '.m4a', '.ogg'],
    nameDe: 'Audio komprimieren',
    shortDescriptionDe: 'Reduzieren Sie die Dateigröße von Musik und Sprachmemos mit intelligenten Bitraten-Profilen ohne spürbaren Qualitätsverlust.',
    titleDe: 'Audio komprimieren online – MP3- & WAV-Dateigröße verkleinern | CoolWave',
    metaDescriptionDe: 'Audio online kostenlos verkleinern. MP3 und WAV komprimieren mit wählbarer Bitrate (64k bis 256k) für E-Mail, WhatsApp und Web.',
    h1De: 'Audiodateien online komprimieren',
    introDe: 'Große Audiodateien schnell und gezielt verkleinern. Reduzieren Sie Speicherplatzbedarf für den Versand per E-Mail oder Messenger durch optimierte Kodierung.',
    howItWorksDe: [
      { step: 1, title: 'Audio auswählen', text: 'Laden Sie Ihre MP3-, WAV- oder FLAC-Datei hoch.' },
      { step: 2, title: 'Kompression wählen', text: 'Wählen Sie Ihre Zielbitrate: 64k (sehr klein) bis 192k (hohe Audioqualität).' },
      { step: 3, title: 'Herunterladen', text: 'Laden Sie die komprimierte Datei herunter und sparen Sie bis zu 80% Speicherplatz.' },
    ],
    faqDe: [
      { question: 'Welche Bitrate eignet sich für Sprache?', answer: 'Für reine Sprachaufnahmen, Diktate und Podcasts genügen 64 oder 96 kbps bei kristallklarer Sprachverständlichkeit.' },
    ],
    privacyExplanationDe: 'Sichere temporäre Verarbeitung. Keine dauerhafte Speicherung Ihrer Aufnahmen.',
    searchKeywordsDe: ['Audio komprimieren', 'MP3 verkleinern', 'Audio Dateigröße reduzieren', 'WAV komprimieren online'],
    supportedFormats: 'MP3, WAV, AAC, FLAC, M4A',
    freeLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 200, maxBatch: 10 },
    processingEngine: 'media-convert',
    browserCapable: false,
    serverRequired: true,
    relatedTools: ['audio-konvertieren', 'video-in-mp3-umwandeln'],
    icon: 'FileAudio',
    status: 'active',
  },
  {
    id: 'video-in-mp3-umwandeln',
    slug: 'video-in-mp3-umwandeln',
    category: 'utilities',
    sourceFormats: ['.mp4', '.mov', '.avi', '.mkv', '.webm'],
    targetFormats: ['.mp3'],
    nameDe: 'Video in MP3 umwandeln',
    shortDescriptionDe: 'Extrahieren Sie die Audiospur aus Videodateien (MP4, MOV, WebM, MKV) und speichern Sie sie als hochwertige MP3-Datei.',
    titleDe: 'Video in MP3 umwandeln online – Audiospur aus Video extrahieren | CoolWave',
    metaDescriptionDe: 'Tonspur aus Video extrahieren. MP4 in MP3, WebM in MP3 kostenlos online umwandeln mit 192 kbps Klangqualität.',
    h1De: 'Video in MP3 umwandeln – Tonspur extrahieren',
    introDe: 'Extrahieren Sie im Handumdrehen den Soundtrack, die Dialoge oder Musik aus Ihren Videos. Unser Konverter trennt die Audiospur verlustarm ab und exportiert eine saubere MP3-Audiodatei.',
    howItWorksDe: [
      { step: 1, title: 'Video hochladen', text: 'Wählen Sie ein Video im Format MP4, MOV, WebM oder MKV aus.' },
      { step: 2, title: 'Extrahieren starten', text: 'Die Audiospur wird mit modernem LAME-MP3-Encoder in 192 kbps extrahiert.' },
      { step: 3, title: 'MP3 anhören & laden', text: 'Spielen Sie die MP3 direkt im Web-Player ab und laden Sie sie herunter.' },
    ],
    faqDe: [
      { question: 'Bleibt die Tonqualität erhalten?', answer: 'Ja, die Audiospur wird mit bis zu 192 kbps oder Originalbitrate extrahiert.' },
    ],
    privacyExplanationDe: 'Videos werden nach der Audiospur-Extraktion umgehend von unseren Servern entfernt.',
    searchKeywordsDe: ['Video in MP3 umwandeln', 'MP4 in MP3', 'Tonspur aus Video schneiden', 'Audio aus Video extrahieren'],
    supportedFormats: 'MP4, MOV, WebM, MKV, AVI zu MP3',
    freeLimits: { maxFileSizeMB: 100, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 500, maxBatch: 5 },
    processingEngine: 'media-convert',
    browserCapable: false,
    serverRequired: true,
    relatedTools: ['audio-konvertieren', 'video-konvertieren'],
    icon: 'Music',
    status: 'active',
    badge: 'Beliebt',
  },

  // =========================================================================
  // VIDEO SUITE (FFmpeg H.264, VP8/VP9, GIF)
  // =========================================================================
  {
    id: 'video-konvertieren',
    slug: 'video-konvertieren',
    category: 'utilities',
    sourceFormats: ['.mp4', '.mov', '.avi', '.mkv', '.webm'],
    targetFormats: ['.mp4', '.webm', '.mov', '.avi', '.mkv', '.gif'],
    nameDe: 'Video konvertieren',
    shortDescriptionDe: 'Konvertieren Sie Videodateien schnell und präzise zwischen MP4, WebM, MOV, AVI und MKV mit universeller Abspielbarkeit.',
    titleDe: 'Video konvertieren online – MP4, WebM, MOV, AVI umwandeln | CoolWave',
    metaDescriptionDe: 'Kostenloser Online-Videokonverter. MP4 in WebM, MOV in MP4, AVI in MP4 schnell und ohne Wasserzeichen umwandeln.',
    h1De: 'Videodateien online konvertieren',
    introDe: 'Bringen Sie Ihre Videos in das passende Format für Webseiten, Smartphones, Fernseher und Schnittprogramme. Mit modernster H.264- und VP8-Videokodierung für maximale Bildschärfe bei optimierter Dateigröße.',
    howItWorksDe: [
      { step: 1, title: 'Video hochladen', text: 'Laden Sie Ihre Video-Datei (z. B. MOV vom iPhone oder MKV) hoch.' },
      { step: 2, title: 'Format wählen', text: 'Wählen Sie das Zielformat: MP4, WebM, MOV, AVI, MKV oder animiertes GIF.' },
      { step: 3, title: 'Downloaden', text: 'Sehen Sie das konvertierte Video in der Vorschau und laden Sie es herunter.' },
    ],
    faqDe: [
      { question: 'Welches Videoformat ist am besten für das Web geeignet?', answer: 'MP4 (H.264/AAC) und WebM (VP8/VP9) werden von praktisch allen modernen Browsern und Mobilgeräten nativ unterstützt.' },
    ],
    privacyExplanationDe: 'Videos werden in temporären Worker-Prozessen transkodiert und streng nach Ablaufzeit gelöscht.',
    searchKeywordsDe: ['Video konvertieren online', 'MOV in MP4 umwandeln', 'MKV in MP4', 'WebM konvertieren', 'Video umwandeln'],
    supportedFormats: 'MP4, MOV, AVI, MKV, WebM',
    freeLimits: { maxFileSizeMB: 100, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 500, maxBatch: 5 },
    processingEngine: 'media-convert',
    browserCapable: false,
    serverRequired: true,
    relatedTools: ['video-komprimieren', 'video-in-mp4-umwandeln', 'video-in-gif-umwandeln'],
    icon: 'Video',
    status: 'active',
  },
  {
    id: 'video-komprimieren',
    slug: 'video-komprimieren',
    category: 'utilities',
    sourceFormats: ['.mp4', '.mov', '.avi', '.mkv', '.webm'],
    targetFormats: ['.mp4'],
    nameDe: 'Video komprimieren',
    shortDescriptionDe: 'Verkleinern Sie Videodateien intelligent per H.264 CRF-Kompression ohne sichtbare Qualitätsverluste.',
    titleDe: 'Video komprimieren online – Videodatei verkleinern kostenlos | CoolWave',
    metaDescriptionDe: 'Video Dateigröße online verringern. MP4 und MOV bis zu 80% verkleinern für E-Mail, Discord und WhatsApp ohne Qualitätsverlust.',
    h1De: 'Videos online komprimieren & verkleinern',
    introDe: 'Große Videoaufnahmen blockieren Speicherplatz und lassen sich oft nicht per Mail oder Messenger versenden. Unser intelligenter Video-Kompressor analysiert Bildraten und Kontraste, um Datenmengen drastisch zu reduzieren.',
    howItWorksDe: [
      { step: 1, title: 'Video hochladen', text: 'Wählen Sie ein großes Video von Ihrem Gerät aus.' },
      { step: 2, title: 'Stufe festlegen', text: 'Wählen Sie zwischen starker Kompression, ausgewogener Balance oder leichter Verkleinerung.' },
      { step: 3, title: 'Fertiges Video laden', text: 'Überprüfen Sie die Größenersparnis in der Vorschau und laden Sie das komprimierte MP4 herunter.' },
    ],
    faqDe: [
      { question: 'Wird die Auflösung verändert?', answer: 'Videos über 1080p werden auf Full HD herunterskaliert, um die perfekte Balance aus Schärfe und Dateigröße zu erzielen.' },
    ],
    privacyExplanationDe: 'Ihre Videos werden vertraulich behandelt und nach der Komprimierung sicher gelöscht.',
    searchKeywordsDe: ['Video komprimieren', 'Video verkleinern online', 'MP4 komprimieren', 'Video für WhatsApp verkleinern'],
    supportedFormats: 'MP4, MOV, WebM, AVI, MKV',
    freeLimits: { maxFileSizeMB: 100, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 500, maxBatch: 5 },
    processingEngine: 'media-convert',
    browserCapable: false,
    serverRequired: true,
    relatedTools: ['video-konvertieren', 'video-in-mp4-umwandeln'],
    icon: 'FileVideo',
    status: 'active',
  },
  {
    id: 'video-in-gif-umwandeln',
    slug: 'video-in-gif-umwandeln',
    category: 'utilities',
    sourceFormats: ['.mp4', '.mov', '.webm', '.avi'],
    targetFormats: ['.gif'],
    nameDe: 'Video in GIF umwandeln',
    shortDescriptionDe: 'Erstellen Sie animierte GIFs aus kurzen Videoclips mit flüssiger Bildrate und optimierter Farbpalette.',
    titleDe: 'Video in GIF umwandeln online – Animiertes GIF erstellen | CoolWave',
    metaDescriptionDe: 'Video kostenlos in GIF umwandeln. MP4 zu GIF erstellen mit anpassbarer Bildrate (FPS) für Webseiten, Social Media und Memes.',
    h1De: 'Video in animiertes GIF umwandeln',
    introDe: 'Verwandeln Sie Videoausschnitte in loopende animierte GIFs. Perfekt für Social Media Posts, Dokumentationen, Blogartikel oder Memes – ganz ohne Wasserzeichen.',
    howItWorksDe: [
      { step: 1, title: 'Clip hochladen', text: 'Wählen Sie ein kurzes Video (MP4, MOV oder WebM).' },
      { step: 2, title: 'Bildrate wählen', text: 'Wählen Sie 10 FPS (kompakt) oder 15 FPS (flüssig).' },
      { step: 3, title: 'GIF speichern', text: 'Sehen Sie das generierte GIF in der Vorschau und laden Sie es sofort herunter.' },
    ],
    faqDe: [
      { question: 'Wie lang sollte das Ausgangsvideo sein?', answer: 'Für beste Ergebnisse und handliche Dateigrößen empfehlen wir Videoclips von 2 bis 15 Sekunden.' },
    ],
    privacyExplanationDe: '100% DSGVO-konforme temporäre Umwandlung.',
    searchKeywordsDe: ['Video in GIF umwandeln', 'MP4 zu GIF online', 'GIF aus Video erstellen', 'Animiertes GIF machen'],
    supportedFormats: 'MP4, MOV, WebM zu GIF',
    freeLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 200, maxBatch: 5 },
    processingEngine: 'media-convert',
    browserCapable: false,
    serverRequired: true,
    relatedTools: ['video-konvertieren', 'video-komprimieren'],
    icon: 'Sparkles',
    status: 'active',
  },
  {
    id: 'video-in-mp4-umwandeln',
    slug: 'video-in-mp4-umwandeln',
    category: 'utilities',
    sourceFormats: ['.mov', '.avi', '.mkv', '.webm', '.flv'],
    targetFormats: ['.mp4'],
    nameDe: 'Video in MP4 umwandeln',
    shortDescriptionDe: 'Konvertieren Sie beliebige Videoformate (MOV, AVI, MKV, WebM) in das universelle Web-Format MP4 (H.264 / AAC).',
    titleDe: 'Video in MP4 umwandeln online – Universal-Konverter | CoolWave',
    metaDescriptionDe: 'Beliebige Videos kostenlos in MP4 umwandeln. MOV, AVI, MKV und WebM in universelles MP4 mit H.264-Codec transformieren.',
    h1De: 'Videos in universelles MP4 umwandeln',
    introDe: 'Manche Videos lassen sich auf bestimmten Geräten nicht öffnen. Konvertieren Sie iPhone-Videos (MOV), Web-Clips (WebM) oder Filmdateien (MKV/AVI) in das weltweit kompatibelste Format MP4.',
    howItWorksDe: [
      { step: 1, title: 'Video hochladen', text: 'Laden Sie Ihre Videodatei hoch.' },
      { step: 2, title: 'Transkodierung', text: 'Unser Server wandelt das Video mit H.264-Videocodec und AAC-Audiocodec um.' },
      { step: 3, title: 'MP4 herunterladen', text: 'Laden Sie Ihr fertiges, überall abspielbares MP4 herunter.' },
    ],
    faqDe: [
      { question: 'Spielt das erzeugte MP4 auf dem iPhone und Android?', answer: 'Ja, H.264 und AAC mit FastStart-Header garantieren sofortige Wiedergabe auf allen Smartphones und Computern.' },
    ],
    privacyExplanationDe: 'Dateien werden nach Abschluss der Konvertierung sofort gelöscht.',
    searchKeywordsDe: ['Video in MP4 umwandeln', 'MOV in MP4 umwandeln', 'AVI in MP4 online', 'MKV in MP4'],
    supportedFormats: 'MOV, AVI, MKV, WebM zu MP4',
    freeLimits: { maxFileSizeMB: 100, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 500, maxBatch: 5 },
    processingEngine: 'media-convert',
    browserCapable: false,
    serverRequired: true,
    relatedTools: ['video-konvertieren', 'mp4-in-webm-umwandeln'],
    icon: 'Video',
    status: 'active',
  },
  {
    id: 'mp4-in-webm-umwandeln',
    slug: 'mp4-in-webm-umwandeln',
    category: 'utilities',
    sourceFormats: ['.mp4', '.mov'],
    targetFormats: ['.webm'],
    nameDe: 'MP4 in WebM umwandeln',
    shortDescriptionDe: 'Konvertieren Sie MP4-Videos in das moderne, quelloffene WebM-Format für HTML5-Webseiten mit VP8/VP9-Videocodec.',
    titleDe: 'MP4 in WebM umwandeln online – HTML5 WebM erstellen | CoolWave',
    metaDescriptionDe: 'MP4 in WebM kostenlos online konvertieren. Optimale Web-Performance und Videoeinbettung mit VP8/VP9 und Vorbis-Audio.',
    h1De: 'MP4 in WebM für das Web umwandeln',
    introDe: 'WebM ist das offene Medienformat für moderne Webseiten und HTML5 `<video>`-Tags. Konvertieren Sie MP4-Dateien in kompakte WebM-Dateien für extrem schnelle Web-Ladezeiten.',
    howItWorksDe: [
      { step: 1, title: 'MP4-Video hochladen', text: 'Wählen Sie Ihr MP4-Video aus.' },
      { step: 2, title: 'In WebM kodieren', text: 'Das Video wird mit VP8/Vorbis kodiert.' },
      { step: 3, title: 'WebM laden', text: 'Laden Sie die WebM-Datei herunter und binden Sie sie in Ihre Website ein.' },
    ],
    faqDe: [
      { question: 'Warum WebM statt MP4 nutzen?', answer: 'WebM erzielt oft kleinere Dateigrößen bei gleicher visueller Qualität und ist lizenzkostenfrei.' },
    ],
    privacyExplanationDe: 'Sichere Ausführung im isolierten Worker-Container.',
    searchKeywordsDe: ['MP4 in WebM umwandeln', 'WebM Konverter online', 'HTML5 Video WebM erstellen', 'MP4 to WebM'],
    supportedFormats: 'MP4, MOV zu WebM',
    freeLimits: { maxFileSizeMB: 100, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 500, maxBatch: 5 },
    processingEngine: 'media-convert',
    browserCapable: false,
    serverRequired: true,
    relatedTools: ['video-in-mp4-umwandeln', 'video-konvertieren'],
    icon: 'FileVideo',
    status: 'active',
  },

  // =========================================================================
  // ARCHIVES (ZIP, 7Z, TAR, GZIP)
  // =========================================================================
  {
    id: 'zip-erstellen',
    slug: 'zip-erstellen',
    category: 'utilities',
    sourceFormats: ['*/*'],
    targetFormats: ['.zip'],
    nameDe: 'ZIP erstellen',
    shortDescriptionDe: 'Bündeln Sie mehrere Dateien und Dokumente in ein kompaktes, universell kompatibles ZIP-Archiv.',
    titleDe: 'ZIP erstellen online – Dateien kostenlos in ZIP packen | CoolWave',
    metaDescriptionDe: 'ZIP online erstellen. Beliebig viele Dateien kostenlos im Browser zu einem ZIP-Archiv komprimieren und bündeln.',
    h1De: 'Dateien in ein ZIP-Archiv packen',
    introDe: 'Fassen Sie mehrere Dokumente, Bilder oder Tabellen zu einer einzigen handlichen ZIP-Datei zusammen. Ideal für E-Mail-Anhänge oder geordneten Datenaustausch – 100% lokal im Browser gepackt.',
    howItWorksDe: [
      { step: 1, title: 'Dateien hinzufügen', text: 'Ziehen Sie beliebig viele Dateien in das Upload-Feld.' },
      { step: 2, title: 'Namen vergeben', text: 'Geben Sie Ihrem Archiv einen Namen (z. B. projekt_dateien).' },
      { step: 3, title: 'ZIP erstellen', text: 'Klicken Sie auf Erstellen und laden Sie die komprimierte ZIP-Datei herunter.' },
    ],
    faqDe: [
      { question: 'Werden meine Dateien auf einen Server geladen?', answer: 'Nein! Das Erstellen des ZIP-Archivs geschieht direkt im Arbeitsspeicher Ihres Browsers via JavaScript.' },
    ],
    privacyExplanationDe: '100% clientseitige Erstellung im Browser. Keine Netzwerkübertragung.',
    searchKeywordsDe: ['ZIP erstellen online', 'Dateien in ZIP packen', 'ZIP Archiv erstellen kostenlos', 'Mehrere Dateien bündeln'],
    supportedFormats: 'Alle Dateitypen',
    freeLimits: { maxFileSizeMB: 100, maxBatch: 50 },
    proLimits: { maxFileSizeMB: 500, maxBatch: 200 },
    processingEngine: 'archive-tool',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['zip-entpacken', '7z-entpacken'],
    icon: 'FolderArchive',
    status: 'active',
  },
  {
    id: 'zip-entpacken',
    slug: 'zip-entpacken',
    category: 'utilities',
    sourceFormats: ['.zip'],
    targetFormats: ['.zip'],
    nameDe: 'ZIP entpacken',
    shortDescriptionDe: 'Öffnen und entpacken Sie ZIP-Archive sicher mit automatischer Prüfung auf Zip-Bombs und Dateibaum-Vorschau.',
    titleDe: 'ZIP entpacken online – ZIP-Dateien sicher öffnen | CoolWave',
    metaDescriptionDe: 'ZIP online entpacken. ZIP-Archive sicher im Webbrowser öffnen, Dateien ansehen und extrahieren mit Schutz vor Schadcode.',
    h1De: 'ZIP-Archiv online entpacken',
    introDe: 'Öffnen Sie ZIP-Archive direkt online, ohne Extra-Software installieren zu müssen. Mit integrierter Sicherheitsprüfung gegen Path Traversal und Decompression-Bombs.',
    howItWorksDe: [
      { step: 1, title: 'ZIP-Datei hochladen', text: 'Wählen Sie das ZIP-Archiv von Ihrem Endgerät aus.' },
      { step: 2, title: 'Inhalt inspizieren', text: 'Die Dateien werden sicher dekomprimiert und in einer Dateiliste angezeigt.' },
      { step: 3, title: 'Herunterladen', text: 'Laden Sie die bereinigten Dateien gebündelt oder einzeln herunter.' },
    ],
    faqDe: [
      { question: 'Was ist eine Decompression Bomb?', answer: 'Eine manipulierte Archivdatei, die entpackt hunderte Gigabyte groß wird, um Systeme lahmzulegen. Unser System filtert solche Risiken vorab heraus.' },
    ],
    privacyExplanationDe: 'Geprüfte, isolierte Extraktion und automatische Bereinigung.',
    searchKeywordsDe: ['ZIP entpacken online', 'ZIP öffnen ohne Programm', 'ZIP Datei extrahieren', 'ZIP Entpacker kostenlos'],
    supportedFormats: 'ZIP-Archive',
    freeLimits: { maxFileSizeMB: 100, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 250, maxBatch: 5 },
    processingEngine: 'archive-tool',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['zip-erstellen', '7z-entpacken', 'tar-entpacken'],
    icon: 'Archive',
    status: 'active',
  },
  {
    id: '7z-entpacken',
    slug: '7z-entpacken',
    category: 'utilities',
    sourceFormats: ['.7z'],
    targetFormats: ['.zip'],
    nameDe: '7Z entpacken (7-Zip)',
    shortDescriptionDe: 'Entpacken Sie hochkomprimierte 7z-Dateien online ohne 7-Zip-Installation auf Ihrem Computer.',
    titleDe: '7Z entpacken online – 7-Zip Dateien kostenlos öffnen | CoolWave',
    metaDescriptionDe: '7Z online entpacken. 7-Zip Archive ohne Zusatzsoftware direkt öffnen und in Standard-Dateien oder ZIP umwandeln.',
    h1De: '7Z-Dateien online entpacken (7-Zip)',
    introDe: '7-Zip (.7z) bietet exzellente Kompressionsraten, lässt sich aber auf vielen Geräten ohne Spezialsoftware nicht öffnen. Unser 7Z-Entpacker liest das Archiv für Sie aus und stellt die Dateien sofort bereit.',
    howItWorksDe: [
      { step: 1, title: '7Z-Datei hochladen', text: 'Laden Sie die .7z-Archivdatei hoch.' },
      { step: 2, title: 'Isoliert entpacken', text: 'Das Archiv wird sicher in einer Sandbox dekomprimiert.' },
      { step: 3, title: 'Dateien sichern', text: 'Laden Sie die extrahierten Dateien als sauberes ZIP herunter.' },
    ],
    faqDe: [
      { question: 'Unterstützt das Tool passwortgeschützte 7z-Dateien?', answer: 'Aus Sicherheitsgründen werden passwortgeschützte 7z-Archive derzeit abgewiesen.' },
    ],
    privacyExplanationDe: '7-Zip Worker isoliert in geschützter Sandbox mit Dateigrößen-Cap.',
    searchKeywordsDe: ['7z entpacken online', '7-Zip Datei öffnen', '7z in ZIP umwandeln', '7z Entpacker'],
    supportedFormats: '7Z-Archive',
    freeLimits: { maxFileSizeMB: 100, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 250, maxBatch: 5 },
    processingEngine: 'archive-tool',
    browserCapable: false,
    serverRequired: true,
    relatedTools: ['zip-entpacken', 'tar-entpacken', 'zip-erstellen'],
    icon: 'Archive',
    status: 'active',
  },
  {
    id: 'tar-entpacken',
    slug: 'tar-entpacken',
    category: 'utilities',
    sourceFormats: ['.tar', '.tar.gz', '.tgz'],
    targetFormats: ['.zip'],
    nameDe: 'TAR & TAR.GZ entpacken',
    shortDescriptionDe: 'Öffnen Sie Linux- und Unix-Tarballs (.tar, .tar.gz, .tgz) unkompliziert unter Windows oder Mac im Browser.',
    titleDe: 'TAR & TAR.GZ entpacken online – Tarball Dateien öffnen | CoolWave',
    metaDescriptionDe: 'TAR und TAR.GZ online entpacken. Linux Tarballs ohne Terminal oder Zusatzsoftware direkt im Browser extrahieren.',
    h1De: 'TAR & TAR.GZ Tarballs online entpacken',
    introDe: 'Entpacken Sie Unix- und Linux-Tarballs (.tar, .tar.gz, .tgz) schnell und sicher im Browser. Wir extrahieren alle enthaltenen Dateien und stellen sie als übersichtliches ZIP-Archiv zum Download bereit.',
    howItWorksDe: [
      { step: 1, title: 'Tarball hochladen', text: 'Laden Sie Ihre .tar oder .tar.gz Datei hoch.' },
      { step: 2, title: 'Archiv dekomprimieren', text: 'Unser System extrahiert den Tarball und prüft alle Pfade.' },
      { step: 3, title: 'Inhalte herunterladen', text: 'Laden Sie die extrahierten Dateien sofort herunter.' },
    ],
    faqDe: [
      { question: 'Was ist der Unterschied zwischen TAR und TAR.GZ?', answer: 'TAR bündelt Dateien ohne Kompression; TAR.GZ komprimiert das TAR-Paket zusätzlich mit GZIP für minimale Dateigröße.' },
    ],
    privacyExplanationDe: 'Temporäre Bearbeitung ohne dauerhafte Aufbewahrung.',
    searchKeywordsDe: ['TAR entpacken online', 'TAR.GZ öffnen', 'Tarball extrahieren', 'TGZ entpacken'],
    supportedFormats: 'TAR, TAR.GZ, TGZ Archive',
    freeLimits: { maxFileSizeMB: 100, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 250, maxBatch: 5 },
    processingEngine: 'archive-tool',
    browserCapable: false,
    serverRequired: true,
    relatedTools: ['gzip-entpacken', 'zip-entpacken', '7z-entpacken'],
    icon: 'Archive',
    status: 'active',
  },
  {
    id: 'gzip-entpacken',
    slug: 'gzip-entpacken',
    category: 'utilities',
    sourceFormats: ['.gz', '.gzip'],
    targetFormats: ['.txt', '.tar', '.csv'],
    nameDe: 'GZIP entpacken (.gz)',
    shortDescriptionDe: 'Dekomprimieren Sie einzelne GZIP-Dateien (.gz) sofort zurück in die ursprüngliche Datei.',
    titleDe: 'GZIP entpacken online – .gz Dateien dekomprimieren | CoolWave',
    metaDescriptionDe: 'GZIP online dekomprimieren. .gz Dateien kostenlos entpacken und Originaldatei (z. B. SQL, CSV, Logfile, TAR) wiederherstellen.',
    h1De: 'GZIP (.gz) Dateien online entpacken',
    introDe: 'Dekomprimieren Sie GZIP-Dateien (.gz) im Handumdrehen. Ob komprimierte Server-Logfiles, Datenbank-Dumps (.sql.gz) oder Datensätze: Stellen Sie die Originaldatei mit einem Klick wieder her.',
    howItWorksDe: [
      { step: 1, title: '.gz Datei hochladen', text: 'Wählen Sie Ihre GZIP-komprimierte Datei aus.' },
      { step: 2, title: 'Dekomprimieren', text: 'Die Datei wird mit nativer zlib-Geschwindigkeit entpackt.' },
      { step: 3, title: 'Datei speichern', text: 'Laden Sie die unkomprimierte Originaldatei herunter.' },
    ],
    faqDe: [
      { question: 'Wird der ursprüngliche Dateiname beibehalten?', answer: 'Ja, die Dateiendung .gz wird entfernt, sodass beispielsweise aus data.csv.gz wieder data.csv wird.' },
    ],
    privacyExplanationDe: '100% sichere Verarbeitung mit Decompression-Bomb-Schutz.',
    searchKeywordsDe: ['GZIP entpacken online', '.gz Datei öffnen', 'GZ entpacken kostenlos', 'GZIP dekomprimieren'],
    supportedFormats: 'GZ, GZIP Dateien',
    freeLimits: { maxFileSizeMB: 100, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 250, maxBatch: 5 },
    processingEngine: 'archive-tool',
    browserCapable: false,
    serverRequired: true,
    relatedTools: ['tar-entpacken', 'zip-entpacken'],
    icon: 'FolderArchive',
    status: 'active',
  },
];
