import { ToolDefinition } from '@/types/tool';

export const UTILITIES_TOOLS: ToolDefinition[] = [
  // =========================================================================
  // TEXT UTILITIES (100% In-Browser)
  // =========================================================================
  {
    id: 'wortzaehler',
    slug: 'wortzaehler',
    category: 'utilities',
    sourceFormats: ['.txt', '.md'],
    targetFormats: ['.txt'],
    nameDe: 'Wortzähler & Textanalyse',
    shortDescriptionDe: 'Analysieren Sie Texte sofort: Wörter, Zeichen mit/ohne Leerzeichen, Absätze, Zeilen und geschätzte Lesezeit.',
    titleDe: 'Wortzähler online – Wörter, Zeichen & Lesezeit zählen | CoolWave',
    metaDescriptionDe: 'Kostenloser Wortzähler und Zeichenzähler. Zählt Wörter, Zeichen, Absätze und berechnet die Lesezeit in Echtzeit im Browser.',
    h1De: 'Wortzähler & Zeichenzähler online',
    introDe: 'Ob Hausarbeit, SEO-Artikel, Tweet oder Vortrag: Mit unserem interaktiven Textanalyse-Tool behalten Sie Längenbegrenzungen im Blick. Die Zählung von Wörtern, Zeichen (mit und ohne Leerzeichen), Absätzen und Lesezeit erfolgt in Echtzeit bei der Eingabe.',
    howItWorksDe: [
      { step: 1, title: 'Text einfügen', text: 'Tippen oder fügen Sie Ihren Text in das Textfeld ein.' },
      { step: 2, title: 'Statistiken ablesen', text: 'Sehen Sie sofort Wörter, Zeichen und die geschätzte Redezeit.' },
      { step: 3, title: 'Ergebnis kopieren', text: 'Kopieren Sie den Text bei Bedarf mit einem Klick.' },
    ],
    faqDe: [
      { question: 'Wie wird die Lesezeit berechnet?', answer: 'Die Lesezeit basiert auf der durchschnittlichen Lesegeschwindigkeit eines Erwachsenen von ca. 200 Wörtern pro Minute.' },
    ],
    troubleshootingDe: [
      { issue: 'Zählen Bindestrich-Wörter als ein oder zwei Wörter?', solution: 'Wörter mit Bindestrich (z. B. „CoolWave-Plattform“) werden standardmäßig als zusammenhängende Texteinheit gewertet.' },
    ],
    privacyExplanationDe: '100% lokale Auswertung im Browser. Ihr Text verlässt Ihr Gerät nicht.',
    searchKeywordsDe: ['Zeichenzähler', 'Wörter zählen online', 'Zeichen zählen ohne Leerzeichen', 'Textlänge prüfen'],
    supportedFormats: 'Text-Eingabe',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'text-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['zeichenzaehler', 'zeilen-zaehlen', 'gross-kleinschreibung-aendern'],
    icon: 'Type',
    status: 'active',
  },
  {
    id: 'zeichenzaehler',
    slug: 'zeichenzaehler',
    category: 'utilities',
    sourceFormats: ['.txt'],
    targetFormats: ['.txt'],
    nameDe: 'Zeichenzähler online',
    shortDescriptionDe: 'Genaue Zeichenzählung für Social Media (X/Twitter, LinkedIn, Instagram) und SEO-Metadaten inklusive Bytes und Zeichen ohne Leerzeichen.',
    titleDe: 'Zeichenzähler online – Zeichen mit & ohne Leerzeichen zählen | CoolWave',
    metaDescriptionDe: 'Kostenloser Zeichenzähler online. Exakte Zählung von Zeichen, Buchstaben, Ziffern und Bytes für Social Media Posts und Textlimits.',
    h1De: 'Zeichenzähler online – Zeichenanzahl sofort prüfen',
    introDe: 'Prüfen Sie Textlängen präzise für Social-Media-Zeichenlimits (Twitter 280 Zeichen, Google Meta Title 60 Zeichen). Unser Zeichenzähler unterscheidet zwischen Zeichen mit und ohne Leerzeichen, zählt Buchstaben, Ziffern und Bytes.',
    howItWorksDe: [
      { step: 1, title: 'Text eingeben', text: 'Fügen Sie Ihren Text in den Editor ein.' },
      { step: 2, title: 'Zeichen prüfen', text: 'Lesen Sie die exakte Zeichenanzahl und Byte-Größe in Echtzeit ab.' },
    ],
    faqDe: [
      { question: 'Werden Emojis als ein Zeichen gezählt?', answer: 'In der Standardanzeige zählt jedes Unicode-Graphem als Zeichen, im Byte-Zähler wird die UTF-8-Codegröße (meist 4 Bytes pro Emoji) dargestellt.' },
    ],
    privacyExplanationDe: '100% lokale Berechnung im Browser ohne Netzwerkübertragung.',
    searchKeywordsDe: ['Zeichenzähler online', 'Zeichen zählen ohne Leerzeichen', 'Twitter Zeichenzähler', 'Zeichenanzahl ermitteln'],
    supportedFormats: 'Text',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'text-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['wortzaehler', 'zeilen-zaehlen', 'leerzeichen-entfernen'],
    icon: 'Type',
    status: 'active',
  },
  {
    id: 'zeilen-zaehlen',
    slug: 'zeilen-zaehlen',
    category: 'utilities',
    sourceFormats: ['.txt', '.csv', '.json'],
    targetFormats: ['.txt'],
    nameDe: 'Zeilen zählen online',
    shortDescriptionDe: 'Zeilenzähler für Text- und Codedateien: Zählt Gesamtzeilen, nicht-leere Zeilen, Leerzeilen und maximale Zeilenlänge.',
    titleDe: 'Zeilen zählen online – Zeilenzähler für Text & Code | CoolWave',
    metaDescriptionDe: 'Kostenloser Zeilenzähler online. Ermittelt Gesamtzeilen, Leerzeilen und gefüllte Zeilen in Listen, Skripten und Textdateien sofort im Browser.',
    h1De: 'Zeilen zählen online – Zeilenanzahl sofort berechnen',
    introDe: 'Zählen Sie die Zeilenanzahl in Textdokumenten, Datentabellen oder Quellcode. Das Tool analysiert Gesamtzeilen, nicht-leere Zeilen, leere Absätze und die durchschnittliche Zeilenlänge.',
    howItWorksDe: [
      { step: 1, title: 'Liste oder Text einfügen', text: 'Fügen Sie Ihren zeilenbasierten Text in das Eingabefeld ein.' },
      { step: 2, title: 'Zeilenauswertung ablesen', text: 'Die Zeilenstatistiken werden sofort ohne Verzögerung berechnet.' },
    ],
    faqDe: [
      { question: 'Werden unterschiedliche Zeilenumbrüche (CRLF vs LF) unterstützt?', answer: 'Ja, sowohl Windows-Zeilenumbrüche (CRLF) als auch Unix/Linux/macOS-Umbrüche (LF) werden einheitlich ausgewertet.' },
    ],
    privacyExplanationDe: '100% In-Browser. Keine Serverübertragung.',
    searchKeywordsDe: ['Zeilen zählen online', 'Zeilenzähler', 'Textzeilen zählen', 'Lines of code zählen'],
    supportedFormats: 'Text / Listen / Code',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'text-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['doppelte-zeilen-entfernen', 'leerzeichen-entfernen', 'wortzaehler'],
    icon: 'AlignLeft',
    status: 'active',
  },
  {
    id: 'gross-kleinschreibung-aendern',
    slug: 'gross-kleinschreibung-aendern',
    category: 'utilities',
    sourceFormats: ['.txt'],
    targetFormats: ['.txt'],
    nameDe: 'Groß-/Kleinschreibung ändern',
    shortDescriptionDe: 'Text in GROSSBUCHSTABEN, kleinbuchstaben, Title Case, camelCase, snake_case oder kebab-case umwandeln.',
    titleDe: 'Groß- und Kleinschreibung ändern – Case Converter online | CoolWave',
    metaDescriptionDe: 'Text online in Groß- oder Kleinschreibung umwandeln. Title Case, camelCase, PascalCase, snake_case und kebab-case mit einem Klick.',
    h1De: 'Groß- und Kleinschreibung ändern online',
    introDe: 'Konvertieren Sie Texte im Handumdrehen in Großbuchstaben (UPPERCASE), Kleinbuchstaben (lowercase), Wortanfänge groß (Title Case), camelCase, snake_case oder kebab-case für Programmierer und Texter.',
    howItWorksDe: [
      { step: 1, title: 'Text einfügen', text: 'Geben Sie den Originaltext in den Editor ein.' },
      { step: 2, title: 'Schreibweise wählen', text: 'Klicken Sie auf den gewünschten Stil (z. B. Title Case oder snake_case).' },
      { step: 3, title: 'Kopieren', text: 'Kopieren Sie den gewandelten Text mit einem Klick in die Zwischenablage.' },
    ],
    faqDe: [
      { question: 'Werden deutsche Umlaute korrekt umgewandelt?', answer: 'Ja, ä, ö, ü und ß werden nach den geltenden deutschen Rechtschreibregeln korrekt in Ä, Ö, Ü und SS/ẞ umgesetzt.' },
    ],
    privacyExplanationDe: '100% lokale Umwandlung im Webbrowser.',
    searchKeywordsDe: ['Groß- und Kleinschreibung ändern', 'Case Converter', 'Text in Großbuchstaben', 'camelCase umwandeln'],
    supportedFormats: 'Text',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'text-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['wortzaehler', 'slug-generator', 'leerzeichen-entfernen'],
    icon: 'Type',
    status: 'active',
  },
  {
    id: 'leerzeichen-entfernen',
    slug: 'leerzeichen-entfernen',
    category: 'utilities',
    sourceFormats: ['.txt'],
    targetFormats: ['.txt'],
    nameDe: 'Leerzeichen entfernen',
    shortDescriptionDe: 'Mehrfache Leerzeichen zusammenfassen, Zeilenanfänge und -enden trimmen oder alle Leerzeichen restlos löschen.',
    titleDe: 'Leerzeichen entfernen online – Text bereinigen & trimmen | CoolWave',
    metaDescriptionDe: 'Leerzeichen online aus Texten entfernen. Doppelte Leerzeichen komprimieren, Leerzeilen entfernen und Textenden trimmen.',
    h1De: 'Leerzeichen entfernen & Text bereinigen',
    introDe: 'Befreien Sie Ihre Texte von störenden doppelten Leerzeichen, Tabulatoren und überflüssigen Leerzeilen. Ideal vor dem Einfügen in Layout-Programme, Datenbanken oder Tabellen.',
    howItWorksDe: [
      { step: 1, title: 'Text einfügen', text: 'Fügen Sie Ihren Text in das Eingabefeld ein.' },
      { step: 2, title: 'Bereinigungsoption wählen', text: 'Wählen Sie zwischen Leerzeichen zusammenfassen, Leerzeilen löschen oder Trimmen.' },
      { step: 3, title: 'Ergebnis übernehmen', text: 'Kopieren Sie den gesäuberten Text sofort.' },
    ],
    faqDe: [
      { question: 'Können auch Leerzeilen gelöscht werden?', answer: 'Ja, die Option „Leerzeilen löschen“ entfernt alle reinen Leerzeilen zwischen Textabsätzen.' },
    ],
    privacyExplanationDe: '100% In-Browser. Keine Speicherung oder Übertragung.',
    searchKeywordsDe: ['Leerzeichen entfernen online', 'Doppelte Leerzeichen löschen', 'Text trimmen', 'Leerzeilen entfernen'],
    supportedFormats: 'Text',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'text-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['doppelte-zeilen-entfernen', 'wortzaehler', 'gross-kleinschreibung-aendern'],
    icon: 'Sliders',
    status: 'active',
  },
  {
    id: 'doppelte-zeilen-entfernen',
    slug: 'doppelte-zeilen-entfernen',
    category: 'utilities',
    sourceFormats: ['.txt', '.csv'],
    targetFormats: ['.txt'],
    nameDe: 'Doppelte Zeilen entfernen',
    shortDescriptionDe: 'Bereinigen Sie Listen von doppelten Einträgen – mit optionaler alphabetischer Sortierung und Groß-/Kleinschreibungs-Option.',
    titleDe: 'Doppelte Zeilen entfernen online – Listen deduplizieren | CoolWave',
    metaDescriptionDe: 'Doppelte Zeilen und Duplikate aus Textlisten online entfernen. Schnelle Deduplizierung mit alphabetischer A-Z Sortierung im Browser.',
    h1De: 'Doppelte Zeilen entfernen & Listen deduplizieren',
    introDe: 'Filtern Sie doppelte Einträge aus Kontaktlisten, URL-Sammlungen oder Keyword-Listen. Behalten Sie die originale Reihenfolge bei oder sortieren Sie die bereinigte Liste automatisch alphabetisch.',
    howItWorksDe: [
      { step: 1, title: 'Liste einfügen', text: 'Fügen Sie die Liste mit einer Zeile pro Eintrag ein.' },
      { step: 2, title: 'Optionen festlegen', text: 'Wählen Sie bei Bedarf Groß-/Kleinschreibung oder Sortierung aus.' },
      { step: 3, title: 'Duplikate filtern', text: 'Klicken Sie auf „Duplikate filtern“ und kopieren Sie die eindeutige Liste.' },
    ],
    faqDe: [
      { question: 'Gibt es ein Zeilenlimit?', answer: 'Das Tool verarbeitet problemlos zehntausende Zeilen direkt im lokalen Arbeitsspeicher Ihres Browsers.' },
    ],
    privacyExplanationDe: '100% In-Browser. Ihre Daten verlassen Ihren Rechner nicht.',
    searchKeywordsDe: ['Doppelte Zeilen entfernen', 'Duplikate filtern online', 'Liste deduplizieren', 'Doppelte Einträge löschen'],
    supportedFormats: 'Text / Listen / CSV',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'text-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['zeilen-zaehlen', 'leerzeichen-entfernen', 'wortzaehler'],
    icon: 'ListFilter',
    status: 'active',
  },
  {
    id: 'text-vergleichen',
    slug: 'text-vergleichen',
    category: 'utilities',
    sourceFormats: ['.txt', '.md'],
    targetFormats: ['.txt'],
    nameDe: 'Text vergleichen (Diff Tool)',
    shortDescriptionDe: 'Vergleichen Sie zwei Textversionen oder Codeabschnitte und sehen Sie Änderungen, Hinzufügungen und Entfernungen farblich markiert.',
    titleDe: 'Text vergleichen online – Diff Tool für Texte & Code | CoolWave',
    metaDescriptionDe: 'Zwei Texte online vergleichen. Kostenloses Diff-Tool visualisiert Unterschiede, hinzugefügte und gelöschte Zeilen farblich in Echtzeit.',
    h1De: 'Text vergleichen – Unterschiede visuell erkennen',
    introDe: 'Finden Sie Unterschiede zwischen zwei Versionen eines Dokuments, Vertragsentwurfs oder Code-Snippets. Unser Online-Diff-Tool stellt Original und überarbeiteten Text nebeneinander dar und hebt alle Modifikationen farblich hervor.',
    howItWorksDe: [
      { step: 1, title: 'Texte einfügen', text: 'Fügen Sie Version A (links) und Version B (rechts) ein.' },
      { step: 2, title: 'Differenz ansehen', text: 'Unterschiede werden zeilenweise automatisch berechnet und farbig hervorgehoben.' },
    ],
    faqDe: [
      { question: 'Können auch Programmiercode oder JSON verglichen werden?', answer: 'Ja, das Diff-Tool vergleicht jeden textbasierten Inhalt zeilengenau.' },
    ],
    privacyExplanationDe: '100% vertraulich: Beide Textversionen verbleiben ausschließlich in Ihrem Browser.',
    searchKeywordsDe: ['Text vergleichen online', 'Diff Tool online', 'Textunterschiede finden', 'Code vergleichen'],
    supportedFormats: 'Text / Code / Dokumente',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'text-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['wortzaehler', 'zeilen-zaehlen', 'json-formatter'],
    icon: 'FileDiff',
    status: 'active',
  },
  {
    id: 'slug-generator',
    slug: 'slug-generator',
    category: 'utilities',
    sourceFormats: ['.txt'],
    targetFormats: ['.txt'],
    nameDe: 'Slug Generator für SEO-URLs',
    shortDescriptionDe: 'Generiert saubere, suchmaschinenfreundliche URL-Slugs aus Titeln – mit automatischer deutscher Umlaut-Konvertierung (ä→ae, ö→oe, ü→ue, ß→ss).',
    titleDe: 'Slug Generator online – SEO URLs aus Titeln generieren | CoolWave',
    metaDescriptionDe: 'SEO Slug Generator online. Wandelt Überschriften in saubere URLs um. Unterstützt deutsche Umlaute (ä, ö, ü, ß) und Bindestrich/Unterstrich.',
    h1De: 'SEO Slug Generator – Saubere Web-URLs erstellen',
    introDe: 'Erstellen Sie perfekte, suchmaschinenoptimierte URLs für Blogs, WordPress, Shopify und Webseiten. Deutsche Sonderzeichen und Umlaute wie ä, ö, ü und ß werden automatisch in suchmaschinenkonforme Buchstabenkombinationen umgewandelt.',
    howItWorksDe: [
      { step: 1, title: 'Titel eingeben', text: 'Geben Sie Ihre Artikelüberschrift oder Ihren Produkttitel ein.' },
      { step: 2, title: 'Optionen wählen', text: 'Wählen Sie Bindestrich (-) oder Unterstrich (_) als Trennzeichen.' },
      { step: 3, title: 'Slug kopieren', text: 'Kopieren Sie den fertigen URL-Slug für Ihr CMS.' },
    ],
    faqDe: [
      { question: 'Wie werden deutsche Umlaute aufgelöst?', answer: 'ä wird zu ae, ö zu oe, ü zu ue und ß zu ss. Alle Satzzeichen und Sonderzeichen werden sauber entfernt.' },
    ],
    privacyExplanationDe: '100% In-Browser. Keine Speicherung.',
    searchKeywordsDe: ['Slug Generator', 'URL Slug erstellen', 'SEO URL Generator', 'Umlaute in URL umwandeln'],
    supportedFormats: 'Text',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'text-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['gross-kleinschreibung-aendern', 'wortzaehler'],
    icon: 'Link2',
    status: 'active',
  },

  // =========================================================================
  // DEVELOPER TOOLS (100% In-Browser)
  // =========================================================================
  {
    id: 'json-formatter',
    slug: 'json-formatter',
    category: 'utilities',
    sourceFormats: ['.json', '.txt'],
    targetFormats: ['.json'],
    nameDe: 'JSON Formatter',
    shortDescriptionDe: 'Formatieren Sie unübersichtlichen JSON-Code sauber mit Einrückungen (2/4 Leerzeichen) oder minimieren Sie ihn.',
    titleDe: 'JSON Formatter online – JSON schön formatieren | CoolWave',
    metaDescriptionDe: 'JSON online formatieren und verschönern (Beautify). Einrückungen mit 2 oder 4 Leerzeichen wählen oder kompakt minimieren.',
    h1De: 'JSON Formatter – Code übersichtlich formatieren',
    introDe: 'Unleserliche einzeilige JSON-Antworten aus REST-APIs sauber strukturieren und formatieren. Unser JSON-Formatter rückt Ihren Code wahlweise mit 2 oder 4 Leerzeichen ein oder minimiert ihn für den Produktionseinsatz.',
    howItWorksDe: [
      { step: 1, title: 'JSON einfügen', text: 'Fügen Sie Ihren JSON-Code in den Editor ein.' },
      { step: 2, title: 'Formatierung wählen', text: 'Wählen Sie 2 oder 4 Leerzeichen oder „Kompakt minimieren“.' },
      { step: 3, title: 'Code kopieren', text: 'Kopieren Sie das formatierte JSON mit einem Klick.' },
    ],
    faqDe: [
      { question: 'Werden Syntaxfehler angezeigt?', answer: 'Ja, bei ungültigem JSON wird die exakte Fehlermeldung ausgegeben.' },
    ],
    privacyExplanationDe: '100% In-Browser Code-Formatierung. Keine Serverübertragung.',
    searchKeywordsDe: ['JSON formatieren', 'JSON beautifier online', 'JSON einrücken', 'JSON minifier'],
    supportedFormats: 'JSON / Text',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'dev-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['json-validator', 'json-in-csv-umwandeln', 'base64-umwandeln'],
    icon: 'Code2',
    status: 'active',
  },
  {
    id: 'json-validator',
    slug: 'json-validator',
    category: 'utilities',
    sourceFormats: ['.json', '.txt'],
    targetFormats: ['.json'],
    nameDe: 'JSON Validator',
    shortDescriptionDe: 'Prüfen Sie JSON-Daten nach RFC 8259 auf Syntaxfehler mit exakter Fehlerposition.',
    titleDe: 'JSON Validator online – JSON-Syntax auf Fehler prüfen | CoolWave',
    metaDescriptionDe: 'JSON online validieren. Syntaxfehler, fehlende Klammern und unzulässige Anführungszeichen sofort erkennen und beheben.',
    h1De: 'JSON Validator – Syntax auf Fehler prüfen',
    introDe: 'Validieren Sie Ihre JSON-Dateien und API-Paylods auf syntaktische Korrektheit. Das Tool lokalisiert fehlerhafte Stellen, überflüssige Kommas und ungültige Schlüssel.',
    howItWorksDe: [
      { step: 1, title: 'JSON einfügen', text: 'Kopieren Sie das zu prüfende JSON in das Eingabefeld.' },
      { step: 2, title: 'Validierung starten', text: 'Klicken Sie auf „JSON Syntax prüfen“.' },
    ],
    faqDe: [
      { question: 'Welcher JSON-Standard wird geprüft?', answer: 'Die Validierung erfolgt streng nach der offiziellen Spezifikation RFC 8259 / ECMA-404.' },
    ],
    privacyExplanationDe: '100% In-Browser Validierung. Keine Speicherung.',
    searchKeywordsDe: ['JSON prüfen online', 'JSON Validator Deutsch', 'JSON Syntax check', 'JSON validieren'],
    supportedFormats: 'JSON',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'dev-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['json-formatter', 'json-in-csv-umwandeln'],
    icon: 'Braces',
    status: 'active',
  },
  {
    id: 'json-in-csv-umwandeln',
    slug: 'json-in-csv-umwandeln',
    category: 'utilities',
    sourceFormats: ['.json'],
    targetFormats: ['.csv'],
    nameDe: 'JSON zu CSV Konverter',
    shortDescriptionDe: 'Konvertieren Sie JSON-Objekt-Arrays in CSV-Tabellen – mit konfigurierbarem Trennzeichen (Komma, Semikolon, Tab) und Download.',
    titleDe: 'JSON in CSV umwandeln – kostenlos online konvertieren | CoolWave',
    metaDescriptionDe: 'JSON online in CSV umwandeln. JSON-Arrays in Excel-kompatible CSV-Dateien exportieren mit Komma- oder Semikolon-Trennzeichen.',
    h1De: 'JSON in CSV umwandeln online',
    introDe: 'Wandeln Sie JSON-Datenstrukturen aus Datenbanken oder APIs in CSV-Dateien um. Öffnen Sie Ihre Daten anschließend direkt in Microsoft Excel, Google Sheets oder LibreOffice Calc.',
    howItWorksDe: [
      { step: 1, title: 'JSON einfügen', text: 'Fügen Sie ein JSON-Array von Objekten ein.' },
      { step: 2, title: 'Trennzeichen wählen', text: 'Wählen Sie Komma (international) oder Semikolon (deutsches Excel).' },
      { step: 3, title: 'CSV exportieren', text: 'Laden Sie die CSV-Datei herunter oder kopieren Sie das Ergebnis.' },
    ],
    faqDe: [
      { question: 'Welches Format muss das JSON haben?', answer: 'Das JSON muss ein Array von gleichartigen Objekten sein, z. B. [{"name": "Anna", "alter": 28}, ...].' },
    ],
    privacyExplanationDe: '100% clientseitige Konvertierung im Browser.',
    searchKeywordsDe: ['JSON in CSV umwandeln', 'JSON zu Excel CSV', 'JSON to CSV converter', 'JSON Tabelle exportieren'],
    supportedFormats: 'JSON zu CSV',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'dev-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['csv-in-json-umwandeln', 'json-formatter'],
    icon: 'FileCode',
    status: 'active',
  },
  {
    id: 'csv-in-json-umwandeln',
    slug: 'csv-in-json-umwandeln',
    category: 'utilities',
    sourceFormats: ['.csv'],
    targetFormats: ['.json'],
    nameDe: 'CSV zu JSON Konverter',
    shortDescriptionDe: 'Wandeln Sie CSV- und TSV-Dateien mit Kopfzeile in saubere JSON-Arrays um – mit automatischer Zahlenerkennung.',
    titleDe: 'CSV in JSON umwandeln – kostenlos online konvertieren | CoolWave',
    metaDescriptionDe: 'CSV online in JSON umwandeln. Konvertiert Tabellen mit Komma, Semikolon oder Tabulator in strukturierte JSON-Objekte.',
    h1De: 'CSV in JSON umwandeln online',
    introDe: 'Konvertieren Sie tabellarische CSV-Exporte aus Excel in strukturierte JSON-Arrays für moderne Webanwendungen und APIs. Das Tool erkennt automatisch Trennzeichen sowie Zahlen und Wahrheitswerte.',
    howItWorksDe: [
      { step: 1, title: 'CSV einfügen', text: 'Kopieren Sie Ihre CSV-Tabelle in den Editor.' },
      { step: 2, title: 'In JSON konvertieren', text: 'Klicken Sie auf den Button, um das strukturierte JSON zu generieren.' },
      { step: 3, title: 'Download oder Kopieren', text: 'Laden Sie die .json-Datei herunter oder kopieren Sie den Code.' },
    ],
    faqDe: [
      { question: 'Werden Zahlen als Zahlen oder Strings formatiert?', answer: 'Numerische Spaltenwerte werden automatisch als echte Zahlen (Number) im JSON typisiert.' },
    ],
    privacyExplanationDe: '100% In-Browser. Ihre geschäftlichen Tabellen werden niemals übertragen.',
    searchKeywordsDe: ['CSV in JSON umwandeln', 'CSV zu JSON Konverter', 'CSV to JSON online', 'Excel CSV in JSON'],
    supportedFormats: 'CSV zu JSON',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'dev-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['json-in-csv-umwandeln', 'json-formatter'],
    icon: 'FileCode',
    status: 'active',
  },
  {
    id: 'base64-umwandeln',
    slug: 'base64-umwandeln',
    category: 'utilities',
    sourceFormats: ['.txt'],
    targetFormats: ['.txt'],
    nameDe: 'Base64 Encoder & Decoder',
    shortDescriptionDe: 'Enkodieren und dekodieren Sie Texte und Datenstrings blitzschnell in und aus dem Base64-Format.',
    titleDe: 'Base64 Encoder & Decoder online – Text umwandeln | CoolWave',
    metaDescriptionDe: 'Base64 online enkodieren und dekodieren. Text sicher in Base64 umwandeln oder Base64-Strings in Klartext dekodieren.',
    h1De: 'Base64 Encoder & Decoder online',
    introDe: 'Konvertieren Sie beliebige Zeichenketten und Texte in das Base64-Format oder dekodieren Sie Base64-Strings zurück in lesbaren UTF-8-Klartext. Unverzichtbar für Webentwickler, API-Tests und Datenübertragungen.',
    howItWorksDe: [
      { step: 1, title: 'Modus wählen', text: 'Wählen Sie Enkodieren (Text zu Base64) oder Dekodieren (Base64 zu Text).' },
      { step: 2, title: 'Text einfügen', text: 'Geben Sie den Textstring in das Eingabefeld ein.' },
      { step: 3, title: 'Ergebnis kopieren', text: 'Kopieren Sie das umgewandelte Ergebnis mit einem Klick.' },
    ],
    faqDe: [
      { question: 'Werden Sonderzeichen und Umlaute unterstützt?', answer: 'Ja, CoolWave nutzt eine vollständige UTF-8-kompatible Enkodierung, sodass auch deutsche Umlaute und Emojis fehlerfrei übertragen werden.' },
    ],
    privacyExplanationDe: '100% In-Browser Enkodierung und Dekodierung.',
    searchKeywordsDe: ['Base64 Decoder', 'Base64 Encoder', 'Base64 Text umwandeln', 'Base64 online Deutsch'],
    supportedFormats: 'Text zu Base64 / Base64 zu Text',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'dev-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['base64-encoder', 'base64-decoder', 'url-encoder', 'jwt-decoder'],
    icon: 'Binary',
    status: 'active',
  },
  {
    id: 'base64-encoder',
    slug: 'base64-encoder',
    category: 'utilities',
    sourceFormats: ['.txt'],
    targetFormats: ['.txt'],
    nameDe: 'Base64 Encoder',
    shortDescriptionDe: 'Text schnell und zuverlässig mit vollständiger UTF-8-Unterstützung in Base64 enkodieren.',
    titleDe: 'Base64 Encoder online – Text in Base64 umwandeln | CoolWave',
    metaDescriptionDe: 'Text online in Base64 umwandeln. Schneller und sicherer Base64-Encoder mit nativer UTF-8-Unterstützung im Browser.',
    h1De: 'Base64 Encoder online – Text enkodieren',
    introDe: 'Konvertieren Sie Passwörter, API-Strings und Texte in das universelle Base64-Format für HTTP Basic Auth, E-Mail-Header oder Dateneinbettung.',
    howItWorksDe: [
      { step: 1, title: 'Klartext eingeben', text: 'Fügen Sie Ihren Text in das Eingabefeld ein.' },
      { step: 2, title: 'Base64 kopieren', text: 'Das Base64-Ergebnis steht sofort bereit.' },
    ],
    faqDe: [
      { question: 'Ist Base64 eine Verschlüsselung?', answer: 'Nein, Base64 ist ein reines Kodierungsverfahren für den sicheren Datentransport, keine kryptografische Verschlüsselung.' },
    ],
    privacyExplanationDe: '100% In-Browser. Keine Netzwerkübertragung.',
    searchKeywordsDe: ['Base64 Encoder', 'Text in Base64 enkodieren', 'Base64 umwandeln'],
    supportedFormats: 'Text',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'dev-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['base64-decoder', 'base64-umwandeln', 'url-encoder'],
    icon: 'Binary',
    status: 'active',
  },
  {
    id: 'base64-decoder',
    slug: 'base64-decoder',
    category: 'utilities',
    sourceFormats: ['.txt'],
    targetFormats: ['.txt'],
    nameDe: 'Base64 Decoder',
    shortDescriptionDe: 'Dekodieren Sie Base64-Strings zurück in lesbaren UTF-8-Klartext.',
    titleDe: 'Base64 Decoder online – Base64 in Text umwandeln | CoolWave',
    metaDescriptionDe: 'Base64 online in Klartext umwandeln. Schneller und zuverlässiger Base64-Decoder für Strings und Webdaten im Browser.',
    h1De: 'Base64 Decoder online – Base64 entschlüsseln',
    introDe: 'Dekodieren Sie Base64-kodierte Daten zurück in lesbaren Klartext mit automatischer Berücksichtigung deutscher Umlaute und Sonderzeichen.',
    howItWorksDe: [
      { step: 1, title: 'Base64 einfügen', text: 'Fügen Sie den kodierten Base64-String ein.' },
      { step: 2, title: 'Klartext ablesen', text: 'Der dekodierte Text wird sofort angezeigt.' },
    ],
    faqDe: [
      { question: 'Was tun bei Fehlermeldung?', answer: 'Stellen Sie sicher, dass keine Leerzeichen oder Zeilenumbrüche im Base64-String enthalten sind.' },
    ],
    privacyExplanationDe: '100% In-Browser. Keine Speicherung.',
    searchKeywordsDe: ['Base64 Decoder online', 'Base64 dekodieren', 'Base64 in Text'],
    supportedFormats: 'Base64 zu Text',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'dev-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['base64-encoder', 'base64-umwandeln', 'jwt-decoder'],
    icon: 'Binary',
    status: 'active',
  },
  {
    id: 'url-encoder',
    slug: 'url-encoder',
    category: 'utilities',
    sourceFormats: ['.txt'],
    targetFormats: ['.txt'],
    nameDe: 'URL Encoder (Percent-Encoding)',
    shortDescriptionDe: 'Enkodieren Sie URLs und Query-Parameter prozentbasiert (RFC 3986) für sichere Web-Links.',
    titleDe: 'URL Encoder online – URLs & Parameter enkodieren | CoolWave',
    metaDescriptionDe: 'URL online enkodieren (Percent-Encoding). Wandelt Leerzeichen und Sonderzeichen in URL-konforme %-Codes nach RFC 3986 um.',
    h1De: 'URL Encoder online – Percent-Encoding für URLs',
    introDe: 'Vermeiden Sie fehlerhafte HTTP-Anfragen, indem Sie Leerzeichen, Umlaute und Sonderzeichen in URL-konforme Prozent-Codes umwandeln.',
    howItWorksDe: [
      { step: 1, title: 'URL eingeben', text: 'Geben Sie die URL oder den Query-Parameter ein.' },
      { step: 2, title: 'Enkodieren', text: 'Kopieren Sie die fertige, prozent-enkodierte Zeichenkette.' },
    ],
    faqDe: [
      { question: 'Was ist der Unterschied zwischen encodeURI und encodeURIComponent?', answer: 'encodeURI belässt Protokollzeichen wie http:// und /, während encodeURIComponent alle Sonderzeichen für Parameter enkodiert.' },
    ],
    privacyExplanationDe: '100% In-Browser. Keine Datenübertragung.',
    searchKeywordsDe: ['URL Encoder online', 'Percent Encoding', 'URL enkodieren', 'URL Sonderzeichen umwandeln'],
    supportedFormats: 'Text / URL',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'dev-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['url-decoder', 'base64-encoder', 'slug-generator'],
    icon: 'Link2',
    status: 'active',
  },
  {
    id: 'url-decoder',
    slug: 'url-decoder',
    category: 'utilities',
    sourceFormats: ['.txt'],
    targetFormats: ['.txt'],
    nameDe: 'URL Decoder',
    shortDescriptionDe: 'Dekodieren Sie prozent-enkodierte URLs (%20, %C3%A4 etc.) zurück in lesbaren Klartext.',
    titleDe: 'URL Decoder online – Prozent-kodierte URLs dekodieren | CoolWave',
    metaDescriptionDe: 'URL online dekodieren. Wandelt %20, %26 und Sonderzeichen zurück in Klartext und entschlüsselt GET-Parameter.',
    h1De: 'URL Decoder online – Percent-Encoding rückgängig machen',
    introDe: 'Dekodieren Sie kryptische URLs mit Prozent-Sequenzen wie %20 (Leerzeichen) oder %2F (Slash) zurück in lesbare Klartext-Adressen.',
    howItWorksDe: [
      { step: 1, title: 'URL einfügen', text: 'Fügen Sie die prozent-kodierte URL ein.' },
      { step: 2, title: 'Klartext ablesen', text: 'Die dekodierte URL steht sofort zur Verfügung.' },
    ],
    faqDe: [
      { question: 'Werden auch UTF-8 Mehrbyte-Zeichen unterstützt?', answer: 'Ja, Sequenzen wie %C3%A4 werden fehlerfrei zu ä dekodiert.' },
    ],
    privacyExplanationDe: '100% In-Browser. Keine Speicherung.',
    searchKeywordsDe: ['URL Decoder online', 'URL dekodieren', 'Prozentzeichen URL entfernen'],
    supportedFormats: 'URL',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'dev-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['url-encoder', 'base64-decoder'],
    icon: 'Link2',
    status: 'active',
  },
  {
    id: 'jwt-decoder',
    slug: 'jwt-decoder',
    category: 'utilities',
    sourceFormats: ['.txt'],
    targetFormats: ['.json'],
    nameDe: 'JWT Decoder (JSON Web Token)',
    shortDescriptionDe: 'Dekodieren und analysieren Sie Header und Payload von JSON Web Tokens (JWT) sicher im Browser ohne Server-Upload.',
    titleDe: 'JWT Decoder online – JSON Web Token sicher dekodieren | CoolWave',
    metaDescriptionDe: 'JWT online sicher dekodieren. Header, Payload Claims und Ablaufdatum (exp) direkt im Browser prüfen. Token verlässt niemals Ihr Endgerät.',
    h1De: 'JWT Decoder online – JSON Web Token analysieren',
    introDe: 'Inspizieren Sie JSON Web Tokens (JWT) auf Ihre Claims, Rollen, Ausstellungszeitpunkte und Gültigkeitsdauer. Höchste Sicherheit: Da das Decoding zu 100% lokal im Browser erfolgt, werden vertrauliche Authentifizierungs-Token niemals an fremde Server übertragen.',
    howItWorksDe: [
      { step: 1, title: 'JWT einfügen', text: 'Kopieren Sie das dreiteilige JWT (Header.Payload.Signature) in das Eingabefeld.' },
      { step: 2, title: 'Claims analysieren', text: 'Header und Payload werden formatiert dargestellt, inklusive Ablaufzeit-Prüfung.' },
    ],
    faqDe: [
      { question: 'Wird mein Secret oder Token auf einen Server geladen?', answer: 'Nein! Die Dekodierung erfolgt zu 100% im Arbeitsspeicher Ihres Browsers.' },
    ],
    privacyExplanationDe: '100% lokale Dekodierung im Browser. Tokens verlassen Ihren Browser niemals.',
    searchKeywordsDe: ['JWT Decoder', 'JSON Web Token dekodieren', 'JWT prüfen online', 'JWT expiration prüfen'],
    supportedFormats: 'JWT String',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'dev-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['base64-decoder', 'json-formatter'],
    icon: 'Key',
    status: 'active',
  },
  {
    id: 'uuid-generator',
    slug: 'uuid-generator',
    category: 'utilities',
    sourceFormats: ['.txt'],
    targetFormats: ['.txt'],
    nameDe: 'UUID Generator (v4)',
    shortDescriptionDe: 'Generieren Sie kryptografisch sichere UUIDs (Version 4) einzeln oder im Stapel – mit oder ohne Bindestriche.',
    titleDe: 'UUID Generator online – v4 UUIDs kostenlos generieren | CoolWave',
    metaDescriptionDe: 'Kostenloser UUID Generator online. Kryptografisch sichere Version 4 UUIDs einzeln oder in Serie generieren. Groß-/Kleinschreibung wählbar.',
    h1De: 'UUID Generator online – Eindeutige IDs generieren',
    introDe: 'Erzeugen Sie universell eindeutige Identifikatoren (UUID v4) nach RFC 4122 mittels kryptografischem Zufallsgenerator (Web Crypto API). Ideal für Datenbank-Primärschlüssel, API-IDs und Transaktionen.',
    howItWorksDe: [
      { step: 1, title: 'Anzahl wählen', text: 'Wählen Sie zwischen 1 und 50 UUIDs.' },
      { step: 2, title: 'Optionen anpassen', text: 'Wählen Sie Groß-/Kleinschreibung und ob Bindestriche enthalten sein sollen.' },
      { step: 3, title: 'Generieren & Kopieren', text: 'Klicken Sie auf Generieren und kopieren Sie die Liste mit einem Klick.' },
    ],
    faqDe: [
      { question: 'Wie wahrscheinlich ist eine Kollision?', answer: 'Die Wahrscheinlichkeit einer doppelten UUID v4 ist praktisch null (1 zu 2^122).' },
    ],
    privacyExplanationDe: '100% In-Browser Generierung mittels Web Crypto API.',
    searchKeywordsDe: ['UUID Generator online', 'UUID v4 generieren', 'GUID Generator online', 'Unique Identifier erstellen'],
    supportedFormats: 'UUID',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'dev-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['hash-generator', 'timestamp-umrechnen'],
    icon: 'Binary',
    status: 'active',
  },
  {
    id: 'hash-generator',
    slug: 'hash-generator',
    category: 'utilities',
    sourceFormats: ['.txt'],
    targetFormats: ['.txt'],
    nameDe: 'Hash Generator (SHA-256, SHA-512, SHA-1)',
    shortDescriptionDe: 'Berechnen Sie kryptografische Hashes (SHA-256, SHA-512, SHA-384, SHA-1) in Echtzeit mittels Web Crypto API.',
    titleDe: 'Hash Generator online – SHA-256, SHA-512, SHA-1 berechnen | CoolWave',
    metaDescriptionDe: 'Kryptografische Hashes online berechnen. SHA-256, SHA-512 und SHA-1 Hashes sofort im Browser via Web Crypto API erzeugen.',
    h1De: 'Hash Generator – Kryptografische Prüfsummen berechnen',
    introDe: 'Erzeugen Sie unumkehrbare kryptografische Hashwerte beliebiger Strings direkt in Ihrem Browser. Unterstützt moderne Hash-Standards wie SHA-256 und SHA-512 zur Verifikation von Datenintegrität.',
    howItWorksDe: [
      { step: 1, title: 'Text eingeben', text: 'Geben Sie den zu hashenden Text ein.' },
      { step: 2, title: 'Hashes berechnen', text: 'Die Prüfsummen werden parallel über die Web Crypto API berechnet.' },
      { step: 3, title: 'Hash kopieren', text: 'Kopieren Sie den gewünschten Hex-Hash mit einem Klick.' },
    ],
    faqDe: [
      { question: 'Ist SHA-256 sicher?', answer: 'Ja, SHA-256 ist der weltweite Industriestandard für digitale Signaturen und Blockchain-Integrität.' },
    ],
    privacyExplanationDe: '100% lokale Hash-Berechnung über die Browser Web Crypto API.',
    searchKeywordsDe: ['Hash Generator online', 'SHA256 Generator', 'SHA512 berechnen', 'MD5 SHA1 online'],
    supportedFormats: 'Text',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'dev-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['uuid-generator', 'base64-umwandeln'],
    icon: 'Hash',
    status: 'active',
  },
  {
    id: 'timestamp-umrechnen',
    slug: 'timestamp-umrechnen',
    category: 'utilities',
    sourceFormats: ['.txt'],
    targetFormats: ['.txt'],
    nameDe: 'Timestamp Converter (Unix Epoch)',
    shortDescriptionDe: 'Rechnen Sie Unix-Timestamps (Sekunden/Millisekunden) in lesbare deutsche Datumsangaben und ISO 8601 um.',
    titleDe: 'Unix Timestamp Converter online – Zeitstempel umrechnen | CoolWave',
    metaDescriptionDe: 'Unix Timestamp online umrechnen. Epoch-Zeitstempel in deutsches Datum (MEZ/MESZ) und ISO 8601 konvertieren mit Live-Uhr.',
    h1De: 'Unix Timestamp Converter – Zeitstempel umrechnen',
    introDe: 'Konvertieren Sie Unix-Epochen-Zeitstempel (Sekunden oder Millisekunden seit dem 1. Januar 1970) in menschlich lesbare Datums- und Uhrzeitangaben für Berlin (MEZ/MESZ) und UTC.',
    howItWorksDe: [
      { step: 1, title: 'Timestamp eingeben', text: 'Geben Sie den 10-stelligen (Sekunden) oder 13-stelligen (Millisekunden) Zeitstempel ein.' },
      { step: 2, title: 'Datum ablesen', text: 'Lesen Sie das umgerechnete Datum in deutscher Lokalzeit, UTC und ISO 8601 ab.' },
    ],
    faqDe: [
      { question: 'Wann tritt das Jahr-2038-Problem auf?', answer: 'Am 19. Januar 2038 um 03:14:07 UTC läuft die 32-Bit-Darstellung von Unix-Timestamps über. Unser Tool nutzt 64-Bit JavaScript Numbers und ist zukunftssicher.' },
    ],
    privacyExplanationDe: '100% In-Browser Zeitrechnung.',
    searchKeywordsDe: ['Unix Timestamp umrechnen', 'Epoch Converter', 'Timestamp in Datum', 'Unix Zeitstempel online'],
    supportedFormats: 'Timestamp',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'dev-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['uuid-generator', 'json-formatter'],
    icon: 'Clock',
    status: 'active',
  },
  {
    id: 'regex-tester',
    slug: 'regex-tester',
    category: 'utilities',
    sourceFormats: ['.txt'],
    targetFormats: ['.txt'],
    nameDe: 'Regex Tester online',
    shortDescriptionDe: 'Testen Sie reguläre Ausdrücke (RegEx) in Echtzeit mit Flag-Auswahl (g, i, m, s) und Trefferanzahl.',
    titleDe: 'Regex Tester online – Reguläre Ausdrücke live testen | CoolWave',
    metaDescriptionDe: 'Kostenloser Regex Tester online. Reguläre Ausdrücke in Echtzeit testen, Treffer und Capture Groups analysieren im Browser.',
    h1De: 'Regex Tester online – Reguläre Ausdrücke evaluieren',
    introDe: 'Testen und debuggen Sie reguläre Ausdrücke (RegEx) in Echtzeit. Prüfen Sie Suchmuster für Validierungen (wie E-Mail-Adressen, Postleitzahlen oder Telefonnummern) direkt gegen Testdaten.',
    howItWorksDe: [
      { step: 1, title: 'Regex eingeben', text: 'Geben Sie Ihr Suchmuster und Flags (z. B. g, i) ein.' },
      { step: 2, title: 'Testtext eingeben', text: 'Fügen Sie den Testtext ein.' },
      { step: 3, title: 'Treffer prüfen', text: 'Sehen Sie alle Treffer und deren Indizes übersichtlich aufgelistet.' },
    ],
    faqDe: [
      { question: 'Welche Regex-Engine wird verwendet?', answer: 'Das Tool verwendet die native ECMAScript RegExp-Engine Ihres Browsers.' },
    ],
    privacyExplanationDe: '100% In-Browser Auswertung. Ihre Testdaten bleiben privat.',
    searchKeywordsDe: ['Regex Tester online', 'Reguläre Ausdrücke testen', 'RegEx Generator', 'Regex debugger'],
    supportedFormats: 'RegEx / Text',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'dev-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['wortzaehler', 'json-formatter'],
    icon: 'Search',
    status: 'active',
  },
  {
    id: 'html-formatter',
    slug: 'html-formatter',
    category: 'utilities',
    sourceFormats: ['.html', '.txt'],
    targetFormats: ['.html'],
    nameDe: 'HTML Formatter & Minifier',
    shortDescriptionDe: 'Formatieren Sie unübersichtlichen HTML-Quellcode mit sauberer Einrückung oder minimieren Sie ihn für schnellere Ladezeiten.',
    titleDe: 'HTML Formatter online – HTML sauber formatieren & minifizieren | CoolWave',
    metaDescriptionDe: 'HTML online formatieren und verschönern (Beautify). HTML-Code sauber einrücken oder für optimale Ladezeiten komprimieren (Minify).',
    h1De: 'HTML Formatter & Minifier online',
    introDe: 'Verschönern Sie unübersichtlichen HTML-Code durch konsistente Tag-Einrückungen oder entfernen Sie überflüssige Leerzeichen und Zeilenumbrüche für maximale Web-Performance.',
    howItWorksDe: [
      { step: 1, title: 'HTML einfügen', text: 'Fügen Sie Ihren HTML-Code in den Editor ein.' },
      { step: 2, title: 'Modus wählen', text: 'Wählen Sie „Sauber einrücken“ oder „Minimieren“.' },
      { step: 3, title: 'Code kopieren', text: 'Kopieren Sie das optimierte HTML mit einem Klick.' },
    ],
    faqDe: [
      { question: 'Bleiben Inline-Stile und Skripte erhalten?', answer: 'Ja, alle Attribute und Elementinhalte bleiben vollständig intakt.' },
    ],
    privacyExplanationDe: '100% In-Browser Codeverarbeitung.',
    searchKeywordsDe: ['HTML Formatter', 'HTML beautifier online', 'HTML einrücken', 'HTML minifier'],
    supportedFormats: 'HTML',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'dev-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['css-formatter', 'javascript-formatter', 'json-formatter'],
    icon: 'FileCode',
    status: 'active',
  },
  {
    id: 'css-formatter',
    slug: 'css-formatter',
    category: 'utilities',
    sourceFormats: ['.css', '.txt'],
    targetFormats: ['.css'],
    nameDe: 'CSS Formatter & Minifier',
    shortDescriptionDe: 'Formatieren Sie CSS-Stylesheets sauber mit standardisierten Regeln oder minimieren Sie sie für schnelles Laden.',
    titleDe: 'CSS Formatter online – CSS formatieren & minifizieren | CoolWave',
    metaDescriptionDe: 'CSS online formatieren und verschönern. Stylesheets sauber einrücken oder für maximale Ladezeiten komprimieren (CSS Minifier).',
    h1De: 'CSS Formatter & Minifier online',
    introDe: 'Bringen Sie Ordnung in Ihre CSS-Stylesheets. Der CSS-Formatter rückt Selektoren und Eigenschaften einheitlich ein oder komprimiert Stylesheets für den produktiven Webseiten-Einsatz.',
    howItWorksDe: [
      { step: 1, title: 'CSS einfügen', text: 'Kopieren Sie Ihr CSS in das Eingabefeld.' },
      { step: 2, title: 'Formatierung anwenden', text: 'Wählen Sie zwischen lesbarer Formatierung und Minifizierung.' },
      { step: 3, title: 'Code übernehmen', text: 'Kopieren Sie das Ergebnis sofort in Ihre Zwischenablage.' },
    ],
    faqDe: [
      { question: 'Werden Kommentare beim Minimieren entfernt?', answer: 'Ja, die Minifier-Option entfernt alle CSS-Kommentare zur Reduzierung der Dateigröße.' },
    ],
    privacyExplanationDe: '100% In-Browser.',
    searchKeywordsDe: ['CSS Formatter', 'CSS beautifier online', 'CSS minifier', 'CSS einrücken'],
    supportedFormats: 'CSS',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'dev-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['html-formatter', 'javascript-formatter'],
    icon: 'FileCode',
    status: 'active',
  },
  {
    id: 'javascript-formatter',
    slug: 'javascript-formatter',
    category: 'utilities',
    sourceFormats: ['.js', '.txt'],
    targetFormats: ['.js'],
    nameDe: 'JavaScript Formatter & Minifier',
    shortDescriptionDe: 'Formatieren Sie JavaScript-Code mit klarer Struktur und Einrückung oder minimieren Sie ihn für Produktions-Bundles.',
    titleDe: 'JavaScript Formatter online – JS formatieren & minifizieren | CoolWave',
    metaDescriptionDe: 'JavaScript online formatieren und verschönern (JS Beautify). Quellcode sauber einrücken oder für schnelle Ladezeiten minimieren.',
    h1De: 'JavaScript Formatter & Minifier online',
    introDe: 'Formatieren Sie unübersichtlichen JavaScript-Code lesbar oder reduzieren Sie die Dateigröße durch Minifizierung von Skripten und JSON-Daten.',
    howItWorksDe: [
      { step: 1, title: 'JavaScript einfügen', text: 'Fügen Sie Ihren JS-Code in den Editor ein.' },
      { step: 2, title: 'Formatieren', text: 'Wählen Sie Einrücken (Beautify) oder Minimieren (Minify).' },
      { step: 3, title: 'Kopieren', text: 'Kopieren Sie den formatierten Code.' },
    ],
    faqDe: [
      { question: 'Wird der Code auf Syntaxfehler geprüft?', answer: 'Ja, grundlegende Formatierungs- und Syntaxstrukturen werden validiert.' },
    ],
    privacyExplanationDe: '100% In-Browser. Ihr Code verlässt Ihr Gerät nicht.',
    searchKeywordsDe: ['JavaScript Formatter', 'JS beautifier online', 'JavaScript minifier', 'JS einrücken'],
    supportedFormats: 'JavaScript / Text',
    freeLimits: { maxFileSizeMB: 10, maxBatch: 1 },
    proLimits: { maxFileSizeMB: 50, maxBatch: 1 },
    processingEngine: 'dev-utility',
    browserCapable: true,
    serverRequired: false,
    relatedTools: ['html-formatter', 'css-formatter', 'json-formatter'],
    icon: 'Code2',
    status: 'active',
  },
];
