'use client';

import React from 'react';
import {
  AlignLeft,
  Archive,
  Binary,
  Blend,
  BookOpen,
  Braces,
  CheckCircle,
  Circle,
  CircleDot,
  Clock,
  Code,
  Code2,
  Combine,
  Crop,
  Edit3,
  EyeOff,
  FileAudio,
  FileCheck,
  FileCode,
  FileCode2,
  FileDiff,
  FileImage,
  FileSearch,
  FileSpreadsheet,
  FileText,
  FileType,
  FileUp,
  FileVideo,
  FlipHorizontal,
  Focus,
  FolderArchive,
  GitCompare,
  Hash,
  Image as ImageIcon,
  Info,
  Key,
  Layers,
  Link2,
  ListFilter,
  Lock,
  Maximize2,
  MessageSquareOff,
  Minimize2,
  Monitor,
  Music,
  Palette,
  Paperclip,
  PenTool,
  Presentation,
  Printer,
  RotateCw,
  ScanText,
  Scissors,
  Search,
  ShieldCheck,
  ShieldOff,
  Shrink,
  Sliders,
  Smartphone,
  Sparkles,
  Split,
  Stamp,
  Star,
  SunMedium,
  Table,
  Trash2,
  Type,
  Unlock,
  Spline,
  Video,
  Wrench,
  Zap,
  ZoomOut,
  LucideProps,
} from 'lucide-react';
import { ToolCategory } from '@/types/tool';

// Direct mapping of tool icon strings to Lucide icon components
const ICON_MAP: Record<string, React.ComponentType<LucideProps>> = {
  AlignLeft,
  Archive,
  Binary,
  Blend,
  BookOpen,
  Braces,
  CheckCircle,
  Circle,
  CircleHalf: CircleDot,
  Clock,
  Code,
  Code2,
  Combine,
  Crop,
  Edit3,
  EyeOff,
  FileAudio,
  FileCheck,
  FileCode,
  FileCode2,
  FileDiff,
  FileImage,
  FileSearch,
  FileSpreadsheet,
  FileText,
  FileType,
  FileUp,
  FileVideo,
  FlipHorizontal,
  Focus,
  FolderArchive,
  GitCompare,
  Hash,
  Image: ImageIcon,
  ImageIcon,
  Info,
  Key,
  Layers,
  Link2,
  ListFilter,
  Lock,
  Maximize2,
  MessageSquareOff,
  Minimize2,
  Monitor,
  Music,
  Palette,
  Paperclip,
  PenTool,
  Presentation,
  Printer,
  RotateCw,
  ScanText,
  Scissors,
  Search,
  ShieldCheck,
  ShieldOff,
  Shrink,
  Sliders,
  Smartphone,
  Sparkles,
  Split,
  Stamp,
  Star,
  SunMedium,
  Table,
  Trash2,
  Type,
  Unlock,
  Vector: Spline,
  Video,
  Wrench,
  Zap,
  ZoomOut,
};

const CATEGORY_DEFAULT_ICONS: Record<ToolCategory, React.ComponentType<LucideProps>> = {
  pdf: FileText,
  images: ImageIcon,
  documents: FileSpreadsheet,
  security: ShieldCheck,
  utilities: Wrench,
  ocr: ScanText,
};

interface ToolIconProps extends LucideProps {
  name?: string;
  category?: ToolCategory;
  className?: string;
}

export function ToolIcon({ name, category, className = 'w-5 h-5', ...props }: ToolIconProps) {
  let IconComponent: React.ComponentType<LucideProps> | undefined;

  if (name && ICON_MAP[name]) {
    IconComponent = ICON_MAP[name];
  } else if (category && CATEGORY_DEFAULT_ICONS[category]) {
    IconComponent = CATEGORY_DEFAULT_ICONS[category];
  } else {
    IconComponent = FileText;
  }

  return <IconComponent className={className} aria-hidden="true" {...props} />;
}
