const fs = require('fs');
const { execSync } = require('child_process');

async function verifyAll() {
  console.log('========================================================');
  console.log('      COOLWAVE FINAL SEO VERIFICATION SUITE             ');
  console.log('========================================================\n');

  // 1. Check robots.txt content on disk & via fetch
  console.log('[1] ROBOTS.TXT CHECK:');
  const robotsTxt = fs.readFileSync('public/robots.txt', 'utf8');
  console.log('public/robots.txt exists on disk: YES');
  console.log('CSS/JS blocked (_next):', robotsTxt.includes('/_next/') ? 'FAIL (blocked)' : 'PASS (not blocked)');
  console.log('Admin blocked (/admin/):', robotsTxt.includes('/admin/') ? 'PASS (blocked)' : 'FAIL');
  console.log('API blocked (/api/):', robotsTxt.includes('/api/') ? 'PASS (blocked)' : 'FAIL');
  console.log('Sitemap declared:', robotsTxt.includes('Sitemap:') ? 'PASS' : 'FAIL');

  // 2. Check sitemap.xml generator
  console.log('\n[2] SITEMAP CHECK:');
  const code = `
    import sitemap from './src/app/sitemap';
    const items = sitemap();
    console.log('Total URLs generated by sitemap():', items.length);
    console.log('Includes /de/kontakt:', items.some(i => i.url.endsWith('/kontakt')));
    console.log('Includes /de/preise:', items.some(i => i.url.endsWith('/preise')));
    console.log('Includes /de/blog:', items.some(i => i.url.endsWith('/blog')));
    console.log('Includes /de/impressum:', items.some(i => i.url.endsWith('/impressum')));
    console.log('Includes all 6 category pages:', items.filter(i => i.url.includes('/kategorie/')).length === 6);
  `;
  const sitemapResult = execSync('npx tsx -e "' + code.replace(/\n/g, ' ') + '"', { cwd: process.cwd() });
  console.log(sitemapResult.toString().trim());

  // 3. Check OpenGraph & Icons assets
  console.log('\n[3] ASSET CHECKS:');
  console.log('public/og-image.png (1200x630) exists:', fs.existsSync('public/og-image.png'));
  console.log('public/icon-512.png (512x512) exists:', fs.existsSync('public/icon-512.png'));

  // 4. Test Metadata Generators directly
  console.log('\n[4] METADATA & SCHEMA GENERATOR UNIT AUDIT:');
  const testMetaCode = `
    import { generatePageMetadata, generateToolMetadata, generateCategoryMetadata, generateWebApplicationSchema, generateOrganizationSchema, generateCollectionPageSchema } from './src/lib/seo';
    import { getToolBySlug } from './src/config/tools.config';
    import { CATEGORIES } from './src/config/categories.config';

    const tool = getToolBySlug('pdf-komprimieren');
    const toolMeta = generateToolMetadata(tool, 'de');
    console.log('Tool Canonical:', toolMeta.alternates?.canonical);
    console.log('Tool OG Image:', toolMeta.openGraph?.images?.[0]?.url);
    console.log('Tool Twitter Image:', toolMeta.twitter?.images?.[0]);

    const pageMeta = generatePageMetadata({ title: 'Preise', description: 'Preise & Tarife', path: '/preise', locale: 'de' });
    console.log('Page Canonical:', pageMeta.alternates?.canonical);
    console.log('Page OG Image:', pageMeta.openGraph?.images?.[0]?.url);

    const orgSchema = generateOrganizationSchema();
    console.log('Organization Schema Logo:', orgSchema.logo);

    const appSchema = generateWebApplicationSchema(tool);
    console.log('WebApplication Schema Image:', appSchema.image);

    const catSchema = generateCollectionPageSchema(CATEGORIES.pdf, 'de');
    console.log('CollectionPage Schema Type:', catSchema['@type']);
  `;
  const metaResult = execSync('npx tsx -e "' + testMetaCode.replace(/\n/g, ' ') + '"', { cwd: process.cwd() });
  console.log(metaResult.toString().trim());

  // 5. Test root redirect
  console.log('\n[5] ROOT REDIRECT STATUS:');
  const resRoot = await fetch('http://localhost:3000/', { redirect: 'manual' });
  console.log('HTTP Status for /:', resRoot.status, '(Location: ' + resRoot.headers.get('location') + ')');

  // 6. Test sample page crawlability
  console.log('\n[6] CRAWLABILITY FROM HOMEPAGE:');
  const homeRes = await fetch('http://localhost:3000/de');
  const homeHtml = await homeRes.text();
  const linkMatches = homeHtml.match(/href="\/de\/([^"]+)"/g) || [];
  const uniqueToolLinks = [...new Set(linkMatches)].filter(l => !l.includes('kategorie') && !l.includes('preise') && !l.includes('kontakt') && !l.includes('impressum') && !l.includes('datenschutz') && !l.includes('agb') && !l.includes('cookie-richtlinie') && !l.includes('blog'));
  console.log('Number of direct HTML tool links discoverable on homepage:', uniqueToolLinks.length);

  console.log('\n========================================================');
  console.log('           SEO AUDIT VERIFICATION COMPLETE              ');
  console.log('========================================================');
}

verifyAll().catch(console.error);
